server:
  port: 8080

spring:
  application:
    name: microservice


    #eureka client
    eureka:
      client:
        serviceUrl:
          defaultZone: http://${REGISTRY_SERVER_SERVICE:localhost}:8761/registry-server/eureka/
        registry-fetch-interval-seconds: 10
        instance-info-replication-interval-seconds: 10
      instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
        lease-renewal-interval-in-seconds: 5  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
        lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
        status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/${spring.application.name}/health/healthCheck #固定端口